version: '3'
services:

  # UCP code
  ucp:
    build:
      context: ./
      dockerfile: ./docker/ucp/Dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    container_name: sf-ucp_app

  # Nginx for the webserver
  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes_from:
      - ucp
    ports:
      - 8080:80
    container_name: sf-ucp_nginx
