version: '3'
services:

  # UCP code
  app:
    build:
      context: ./
      dockerfile: ./docker/ucp/Dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    container_name: app

  # Nginx for the webserver
  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80
    container_name: nginx
